data:
  max_len: 1022
  batch_size: 64
  num_workers: 4
  train_epoch_len: 256000
  #需要修改新数据位置
  train_path: /home/yunlongli/code/UTR-LM/data/Fivespecies_Sample_Cao_all_train.fasta
  valid_path: /home/yunlongli/code/UTR-LM/data/Fivespecies_Sample_Cao_all_val.fasta

loss:
  mlm_loss:
    weight: 1.0
  #secstr_loss:
    #weight: 1.0
  #energy_loss:
    #weight: 0.5

optimizer:
  lr: 1.0e-5

scheduler:
  type: cosine
  lr_cosine_length: 75000

#model:
  #num_layers: 6
  #embed_dim: 256
 # attention_heads: 16
 # token_dropout: true
 # has_energy_head: true
 # has_ss_head: true