data:
  max_len: 1022
  batch_size: 32
  num_workers: 16
  train_epoch_len: 256000
  #需要修改新数据位置
  train_path: /home/yunlongli/code/protexp-dev/Data/Pretrained_Data/Fivespecies_Cao_energy_structure_CaoEnergyNormalDist_255795sequence_train.fasta
  valid_path: /home/yunlongli/code/protexp-dev/Data/Pretrained_Data/Fivespecies_Cao_energy_structure_CaoEnergyNormalDist_255795sequence_valid.fasta

loss:
  mlm_loss:
    weight: 1.0
  #secstr_loss:
    #weight: 1.0
  #energy_loss:
    #weight: 0.5

optimizer:
  lr: 1.0e-5

scheduler:
  type: plateau
  lr_factor: 0.1
  lr_patience: 10
  lr_min: 1.0e-7

#model:
  #num_layers: 6
  #embed_dim: 256
 # attention_heads: 16
 # token_dropout: true
 # has_energy_head: true
 # has_ss_head: true